default:
    just --list

run *ARGS:
    nix-shell -vvvvvvv -p pkl --run "pkl {{ARGS}}"

hammer *ARGS:
    #!/usr/bin/env bash
    set -euxo pipefail
    pushd $(git rev-parse --show-toplevel)
    nix run github:jtojnar/nixpkgs-hammering pkl -- -e explicit-phases {{ARGS}}
    popd

review *ARGS:
    nix-shell -p nixpkgs-review --run "nixpkgs-review {{ARGS}}"

format:
    nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt package.nix"
